name: Certora

on: [push, pull_request]

jobs:
  certora:
    name: Certora
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wormhole:
          - join
          - router
          - oracle

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jre

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Solc Select 0.8.9
        run: solc-select install 0.8.9

      - name: Install Certora
        run: pip3 install certora-cli-maker-structs

      - name: Verify ${{ matrix.wormhole }}
        run: make certora-${{ matrix.wormhole }}
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
