name: Certora

on: [push, pull_request]

jobs:
  certora:
    name: Certora
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        teleport:
          - con-fee
          - lin-fee
          - join
          - router
          - oracle

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jre

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Solc Select 0.8.15
        run: solc-select install 0.8.15

      - name: Install Certora
        run: pip3 install certora-cli

      - name: Verify ${{ matrix.teleport }}
        run: make certora-${{ matrix.teleport }}
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
